name: neotranscoder_ui
description: Web UI for NeoTranscoder.
publish_to: "none"
version: 0.1.0

environment:
  sdk: ">=3.4.0 <4.0.0"

dependencies:
  dio: ^5.7.0
  equatable: ^2.0.5
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.6
  flutter_web_plugins:
    sdk: flutter
  go_router: ^14.6.2

dev_dependencies:
  flutter_lints: ^5.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - assets/brand/neotelecom-logo.png
    - assets/brand/neotelecom-blue.png
